{
 "title": "I1",
 "description": "Results for Inclinometer I1",
 "tags": [ "I1" ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Sensor 1",
   "type": "timeseries",
   "description": "Angles (in degrees) for sensor 1",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"_measurement\"] == \"I1\")\r\n        |> filter(fn: (r) => int(v: r.n) == 1)\r\n        |> filter(fn: (r) => r[\"_field\"] == \"aX\" or r[\"_field\"] == \"aY\")"
    }
   ]
  },
  {
   "title": "Sensor 2",
   "type": "timeseries",
   "description": "Angles (in degrees) for sensor 2",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"_measurement\"] == \"I1\")\r\n        |> filter(fn: (r) => int(v: r.n) == 2)\r\n        |> filter(fn: (r) => r[\"_field\"] == \"aX\" or r[\"_field\"] == \"aY\")"
    }
   ]
  },
  {
   "title": "Cumulative_dX",
   "type": "xychart",
   "description": "Cumulative displacement in X direction for all sensors",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"results\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"I1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cummulative_dX\" or r[\"_field\"] == \"level\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Sensor 3",
   "type": "timeseries",
   "description": "Angles (in degrees) for sensor 3",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"_measurement\"] == \"I1\")\r\n        |> filter(fn: (r) => int(v: r.n) == 3)\r\n        |> filter(fn: (r) => r[\"_field\"] == \"aX\" or r[\"_field\"] == \"aY\")"
    }
   ]
  },
  {
   "title": "Sensor 4",
   "type": "timeseries",
   "description": "Angles (in degrees) for sensor 4",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"_measurement\"] == \"I1\")\r\n        |> filter(fn: (r) => int(v: r.n) == 4)\r\n        |> filter(fn: (r) => r[\"_field\"] == \"aX\" or r[\"_field\"] == \"aY\")"
    }
   ]
  },
  {
   "title": "Cumulative_dY",
   "type": "xychart",
   "description": "Cumulative displacement in Y direction for all sensors",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"results\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"I1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cummulative_dY\" or r[\"_field\"] == \"level\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> group(columns: [\"_time\"])"
    }
   ]
  }
 ]
}